[variables]
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_20", "php83", "php83Extensions.pdo_pgsql", "php83Extensions.curl"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["echo pre-built dist in repo - skipping build"]

[start]
cmd = "node dist/index.cjs"