[variables]
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_20", "php83", "php83Packages.pgsql", "php83Packages.curl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/index.cjs"
